- name: Configure Network Interface
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify: Reboot

- name: Configure Hostname
  hostname:
    name: "{{host_name}}"
  notify: Reboot
